server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
